name: Practiva de eventos

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"

jobs:
  cat-text:
    runs-on: ubuntu-latest
    steps:
      - name: checkout del codigo
        uses: actions/checkout@v4

      - name: cat del archivo
        run: cat src/text1.txt